apiVersion: v1
kind: Namespace
metadata:
  name: dapr-system
  annotations:
    scheduler.alpha.kubernetes.io/defaultTolerations: '[{"key": "reservedFor", "operator": "Equal", "effect": "NoSchedule", "value": "eShopOnDapr"}]'
