#helm install prometheus prometheus-community/kube-prometheus-stack
#helm install kube-state-metrics prometheus-community/kube-state-metrics
#helm install win-exporter prometheus-community/prometheus-windows-exporter
# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: windows-demo-apps
# ---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: kube-state-metrics
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: prometheus
    release: prometheus
spec:
  staticConfigs:
    - labels:
        job: kube-state-metrics
      targets:
        - prometheus-kube-state-metrics.default.svc.cluster.local:8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor 
metadata:
  name: prometheus-windows-exporter
  labels:
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus-windows-exporter
    release: prometheus
spec:
  attachMetadata:
    node: false
  endpoints:
  - port: metrics
    scheme: http
  jobLabel: jobLabel
  selector:
    matchLabels:
      app.kubernetes.io/instance: win-exporter
      app.kubernetes.io/name: prometheus-windows-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-demo-monitor
  labels:
    release: prometheus  
spec:
  attachMetadata:
    node: false
  endpoints:
  - port: metrics
    scheme: http
    interval: 15s  
    path: /metrics
  selector:
    matchLabels:
      app: prometheus-demo
  jobLabel: demo      
  namespaceSelector:
    any: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtheus-demo
  namespace: windows-demo-apps
  labels:
    app: prometheus-demo    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-demo
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: prometheus-demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: prometheus-demo
        image: bjdcsa.azurecr.io/otel-demo:win-0ced255b
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        - containerPort: 9090
        env:
        - name: APP_INSIGHTS_CONNECTION_STRING
          value: ""
        resources:
          limits:
            memory: "512Mi"
            cpu: "2"
          requests:
            memory: "64Mi"
            cpu: "0.25"
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
      - key: role
        operator: Equal
        value: applications
        effect: NoSchedule            
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-demo-svc
  namespace: windows-demo-apps
  labels:
    app: prometheus-demo  
  annotations:
   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: prometheus-demo
  ports:
  - port: 80
    targetPort: 5000
    name: web
  - port: 9090
    targetPort: 9090
    name: metrics
  type: LoadBalancer
