apiVersion: apps/v1
kind: Deployment
metadata:
  name: nanoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nanoserver
  template:
    metadata:
      labels:
        app: nanoserver
    spec:
      containers:
      - name: nanoserver
        image: mcr.microsoft.com/windows/nanoserver:ltsc2022
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "1024Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "1024m"           
      nodeSelector:
        kubernetes.io/os: windows
        kubernetes.io/role: agent
        type: virtual-kubelet
      tolerations:
      - key: virtual-kubelet.io/provider
        operator: Equal
        value: azure
        effect: NoSchedule