apiVersion: v1
kind: Namespace
metadata:
  name:  windows-demo-apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apsnetapp
  namespace: windows-demo-apps
  labels: 
   web_server: iis
   os: windows2022  
   app: apsnetapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apsnetapp
  template:
    metadata:
      labels:
        app: apsnetapp
    spec:
      containers:
      - image: mcr.microsoft.com/dotnet/samples:aspnetapp
        name: apsnetapp
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1024m"        
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
      - key: role
        operator: Equal
        value: applications
        effect: NoSchedule
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetapp-svc
  namespace: windows-demo-apps
  labels: 
    app: apsnetapp
spec:
  selector:
    app: apsnetapp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    name: web
  type: ClusterIP
