apiVersion: v1
kind: Pod
metadata:
  name: iis-windows2022
  labels: 
   web_server: iis
   os: windows2022
spec:
  containers:
  - image: mcr.microsoft.com/windows/servercore/iis:windowsservercore-ltsc2022
    name: iis
    ports:
    -  containerPort: 80
  nodeSelector:
   kubernetes.io/os: windows
  tolerations:
  - key: role
    operator: Equal
    value: applications
    effect: NoSchedule