apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: managedpvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: acstor-esan
  resources:
    requests:
      storage: 100Gi