apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqlserver
spec:
    serviceName: mssqlsvc
    replicas: 1
    selector:
      matchLabels:
        app: sqlserver
    template:
      metadata:
        labels: 
          app: sqlserver
      spec:
        terminationGracePeriodSeconds: 10
        initContainers:
        - name: volume-permissions
          image: busybox
          command: ['sh', '-c', 'chmod -R 775 /var/opt/mssql']
          volumeMounts:
          - name: mssql-pv-claim
            mountPath: /var/opt/mssql
        containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-18.04
          ports:
          - containerPort: 1433
          env:
          - name: MSSQL_DATA_DIR
            value: "/var/opt/mssql/data"
          - name: MSSQL_LOG_DIR
            value: "/var/opt/mssql/log"
          - name: MSSQL_PID
            value: "Developer"
          - name: ACCEPT_EULA
            value: 'Y'
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql 
                key: SA_PASSWORD 
          volumeMounts:
            - name: mssql-pv-claim
              mountPath: /var/opt/mssql
          securityContext:
            runAsUser: 10001 
            runAsGroup: 0
        volumes:
        - name: mssql-pv-claim
          persistentVolumeClaim:
            claimName: azure-managed-disk
---
apiVersion: v1
kind: Service
metadata:
  name: mssqlsvc
  labels: 
   app: sqlserver
spec:
  selector:
    app: sqlserver
  ports:
  - port: 1433
    targetPort: 1433
    protocol: TCP
  type: LoadBalancer