apiVersion: v1
kind: Pod
metadata:
  name: sqlserver
  labels:
    app: sqlserver
spec:
    containers:
    - name: sqlserver
      image: microsoft/mssql-server-linux
      ports:
      - containerPort: 1433
      env:
      - name: ACCEPT_EULA
        value: 'Y'
      - name: SA_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mssql 
            key: SA_PASSWORD 
---
apiVersion: v1
kind: Service
metadata:
  name: mssqlsvc
spec:
  selector:
    app: sqlserver
  ports:
  - port: 1433
    targetPort: 1433
    protocol: TCP
  type: NodePort