apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: httpbin
spec:
  paused: true
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        image: bjd145/httpbin:latest
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
          runAsNonRoot: true
          readOnlyRootFilesystem: true
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "2"
          requests:
            memory: "128Mi"
            cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: httpbinsvc
spec:
  selector:
    app: httpbin
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
