apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-devops-serviceaccount
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: azure-devops-role
rules:
- apiGroups: ["*"] 
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["*"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["*"]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["*"]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: azure-devops-role-binding
subjects:
- kind: ServiceAccount
  name:  azure-devops-serviceaccount
roleRef:
  kind: Role 
  name: azure-devops-role
  apiGroup: rbac.authorization.k8s.io
