apiVersion: v1
kind: PersistentVolume
metadata:
  name: bjd-nfs-blobstorage-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=3
    - proto=tcp
    - sec=sys
    - nolock
  nfs:
    server: bjdnfs.blob.core.windows.net
    path: /bjdnfs/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bjd-nfs-blobstorage-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels:
      type: nfs
---
kind: Pod
apiVersion: v1
metadata:
  name: bjdutils-nfs-blobstorage
spec:
  containers:
  - name: bjdutils-nfs-blobstorage
    image: bjd145/utils:latest
    volumeMounts:
    - mountPath: "/mnt/nfs"
      name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: bjd-nfs-blobstorage-pvc
