apiVersion: v1
kind: PersistentVolume
metadata:
  name: bjd-nfs-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.5.100.4
    path: /exports/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bjd-nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
  selector: 
    matchLabels:
      type: nfs
---
kind: Pod
apiVersion: v1
metadata:
  name: bjdutils-nfs
spec:
  containers:
  - name: bjdutils-nfs
    image: bjd145/utils:latest
    volumeMounts:
    - mountPath: "/mnt/nfs"
      name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: bjd-nfs-pvc
