apiVersion: v1
kind: Secret
metadata:
  name: azfiles-secret
type: Opaque 
data:
 azurestorageaccountname: Ympkc2hhcmVzMDAyCg==
 azurestorageaccountkey: LzN3RUFJR1ZUVHJ......
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-files
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  containers:
    - name: myfrontend
      image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
      volumeMounts:
      - mountPath: "/mnt/azure"
        name: volume
  volumes:
    - name: volume
      azureFile:
        secretName: azfiles-secret
        shareName: simple
