apiVersion: v1
kind: PersistentVolume
metadata:
  name: localdisk-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: localdisk-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: localstorage-demo
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: localdisk-pvc
  containers:
    - name: my-app
      image: nginx
      volumeMounts:
        - mountPath: "/var/www/html"
          name: my-storage
