apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-terraform
  namespace: crossplane-system
spec:
  package: xpkg.upbound.io/upbound/provider-terraform:0.1.0
  controllerConfigRef:
    name: terraform-config
---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: terraform-config
  labels:
    app: crossplane-provider-terraform
spec:
  args: ["-d"]
---