---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: persistent-storage
spec:
  storageClassName: azurefile-csi-nfs
  accessModes: [ "ReadWriteMany" ]
  resources:
    requests:
      storage: 100Gi