apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-files
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: azurefile-csi-nfs
  csi:
    driver: file.csi.azure.com
    volumeHandle:  {{ print .Values.STORAGE_ACCOUNT_NAME "_" .Values.STORAGE_CONTAINER_NAME }}
    volumeAttributes:
      resourceGroup: {{ .Values.RESOURCE_GROUP }}
      storageAccount:  {{ .Values.STORAGE_ACCOUNT_NAME }}
      shareName: {{ .Values.STORAGE_CONTAINER_NAME }}
      clientID: {{ .Values.ARM_WORKLOAD_APP_ID }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-files
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-files
  storageClassName: azurefile-csi-nfs