version: '3'

vars:
  DEFAULT_TAG: "Private Multi-region ACR Environment"
  
tasks:
  default:
    desc: Calls `task --list` 
    cmds:
    - task --list

  up:
    desc: Creates a {{.TAGS}} demo
    cmds:
    - terraform init
    - task: apply
      vars:
        TAGS: '{{.TAG_FOR_RUN}}'
    vars: 
      TAG_FOR_RUN: '{{default .DEFAULT_TAG .TAGS }}'
      
  apply:
    desc: Applies the Terraform templates
    cmds:
    - terraform apply -auto-approve -compact-warnings
        -var "tags={{.TAG_FOR_RUN}}" 
    vars: 
      TAG_FOR_RUN: '{{default .DEFAULT_TAG (split " " .CLI_ARGS)._2 }}'

  refresh:
    desc: Refresh the Terraform values
    cmds:
    - terraform refresh -compact-warnings
        -var "tags={{.TAG_FOR_RUN}}" 
    vars: 
      TAG_FOR_RUN: '{{default .DEFAULT_TAG (split " " .CLI_ARGS)._2 }}'

  down:
    desc: Destroys all Azure resources and cleans up Terraform
    cmds:
    - az group list --tag Application="{{.TAG_FOR_DELETE}}" --query "[].name" -o tsv | xargs -ot -n 1 az group delete -y --verbose --no-wait -n  || true
    - rm -rf terraform.tfstate.d .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info || true
    vars:
      TAG_FOR_DELETE: '{{default .DEFAULT_TAG .TAGS }}'
