apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simplenodeapp
spec:
  template:
    metadata:
      labels:
        name: simpleNodeApp
    spec:
      containers:
      - name: simplenodeapp
        image: bjd145/nodeapi
        ports:
        - containerPort: 3000     
---
apiVersion: v1
kind: Service
metadata:
  name: simplenodesvc 
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    name: simpleNodeApp

