apiVersion: apps/v1
kind: Deployment
metadata:
  name: blobfuse-test
spec:
  replicas: 3
  minReadySeconds: 5
  selector:
    matchLabels:
      app: blobfuse-test
  template:
    metadata:
      labels:
        app: blobfuse-test
    spec:
      serviceAccountName: {{ print .Values.APP_NAME "-app-identity" }}
      restartPolicy: Always
      containers:
      - image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
        name: blobfuse-test
        volumeMounts:
        - name: persistent-storage
          mountPath: "/opt/blob"
          readOnly: false
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: pvc-blob

