---
kind: Pod
apiVersion: v1
metadata:
  name: blobfuse01
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: {{ print .Values.APP_NAME "-app-identity" }}
  containers:
  - image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    name: blobfuse-test
    volumeMounts:
    - name: persistent-storage
      mountPath: "/mnt/blob"
      readOnly: false
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: pvc-blob
---
kind: Pod
apiVersion: v1
metadata:
  name: blobfuse02
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: {{ print .Values.APP_NAME "-app-identity" }}
  containers:
  - image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
    name: blobfuse-test
    volumeMounts:
    - name: persistent-storage
      mountPath: "/mnt/blob"
      readOnly: false
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: pvc-blob
