apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: azureblob-fuse-premium-custom
  csi:
    driver: blob.csi.azure.com
    volumeHandle:  {{ print .Values.STORAGE_ACCOUNT_NAME "_" .Values.STORAGE_CONTAINER_NAME }}
    volumeAttributes:
      resourceGroup: {{ .Values.RESOURCE_GROUP }}
      storageAccount:  {{ .Values.STORAGE_ACCOUNT_NAME }}
      containerName: {{ .Values.STORAGE_CONTAINER_NAME }}
      protocol: fuse
    nodeStageSecretRef:
      name: {{ print .Values.STORAGE_ACCOUNT_NAME "-creds" | quote }}
      namespace: kube-system
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-blob
  storageClassName: azureblob-fuse-premium-custom