apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azureblob-fuse-premium
  resourceVersion: "30962"
parameters:
  skuName: Premium_LRS
provisioner: blob.csi.azure.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
    - --use-attr-cache=true
    - --cancel-list-on-mount-seconds=10
    - -o attr_timeout=120
    - -o entry_timeout=120
    - -o negative_timeout=120
    - --log-level=LOG_WARNING
    - --cache-size-mb=1000

