apiVersion: v1
kind: PersistentVolume
metadata:
 name: nfsvol001
spec:
 capacity: 
  storage: 5Gi
 accessModes:
 - ReadWriteOnce
 nfs:
  path: /exports/kube
  server: 10.2.1.2
 persistentVolumeReclaimPolicy: Recycle 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: nfs-pvc
spec:
 resources:
  requests:
   storage: 1Gi
 accessModes:
  - ReadWriteOnce
 storageClassName: ""
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sqlserver
spec:
    serviceName: mssqlsvc
    replicas: 1
    template:
      metadata:
        labels: 
          app: sqlserver
      spec:
        containers:
        - name: sqlserver
          image: mcr.microsoft.com/mssql/server:2017-latest
          ports:
          - containerPort: 1433
          env:
          - name: ACCEPT_EULA
            value: 'Y'
          - name: SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mssql 
                key: SA_PASSWORD 
          volumeMounts:
            - name: mssql-pv-claim
              mountPath: /var/opt/mssql
        volumes:
        - name: mssql-pv-claim
          persistentVolumeClaim:
            claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mssqlsvc
  labels: 
   app: sqlserver
spec:
  selector:
    app: sqlserver
  ports:
  - port: 1433
    targetPort: 1433
    protocol: TCP
  type: NodePort
