#
#Reference - https://github.com/mosabami/aks-adv-workshop-yaml-files
#CSI Installation - https://azure.github.io/secrets-store-csi-driver-provider-azure/getting-started/installation/#deployment-using-helm
#Requires - AAD Pod Identity
#
apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: key-vault-secret-env
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: <key vault name>
    objects:  |
      array:
        - |
          objectName: k8s-secret-demo
          objectType: secret
    tenantId: <tenant id>
  secretObjects:
  - secretName: key-vault-secret
    type: Opaque
    data:
    - objectName: k8s-secret-demo
      key: secret-content