version: '3'

env:
  TAG: AKS environment with Fleet for Multi-Region Management
  DEFAULT_REGION: canadacentral

tasks:
  up:
    desc: Builds a {{.TAG}}  Demo
    cmds:
    - task: init
    - task: apply
    - task: creds
    vars:
      HUB_REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'

  init: 
    desc: Initializes Terraform
    cmds:
    - terraform -chdir=./infrastructure/multiregion-demo workspace new {{.HUB_REGION}} || true
    - terraform -chdir=./infrastructure/multiregion-demo workspace select {{.HUB_REGION}}
    - terraform -chdir=./infrastructure/multiregion-demo init
    vars:
      HUB_REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'

  apply: 
    desc: Applies Terraform configuration
    cmds: 
    - terraform -chdir=./infrastructure/multiregion-demo apply -auto-approve -var "tags={{.TAG}}" -var-file="regions.tfvars"
    vars:
      HUB_REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'

  plan:
    desc: Reviews Terraform plan
    cmds:
    - terraform -chdir=./infrastructure/multiregion-demo plan -var "tags={{.TAG}}" -var "hub_region={{.HUB_REGION}}" -var-file="regions.tfvars"
    vars:
      HUB_REGION: '{{default .DEFAULT_REGION .CLI_ARGS}}'
    
  creds:
    desc: Grab AKS credentials 
    cmds:
    - az fleet member list -f {{.FLEET}} -g {{.RG}} -o tsv --query '[].clusterResourceId' | awk -F/ '{ print "az aks get-credentials -g " $5 " -n " $9 " -f " $9 }' | xargs -n 1 -d '\n' bash -c "$@"
    - az fleet member list -f {{.FLEET}} -g {{.RG}} -o tsv --query '[].name' | xargs bash -c 'sed -i s/devicecode/azurecli/g $0'
    vars:
      RG: 
        sh: terraform -chdir=./infrastructure/multiregion-demo output -raw FLEET_RESOURCE_GROUP
      FLEET: 
        sh: terraform -chdir=./infrastructure/multiregion-demo output -raw FLEET_NAME

  down:
    desc: Destroys all Azure resources and cleans up Terraform
    cmds:
    - az group list --tag Application="{{.TAG}}" --query "[].name" -o tsv | xargs -ot -n 1 az group delete -y --no-wait --verbose -n || true
    - cd ./infrastructure/multiregion-demo; rm -rf terraform.tfstate.d .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info || true
