apiVersion: v1
kind: Namespace
metadata:
  name: pi-job-test
  labels:
    istio.io/rev: asm-1-21
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
  namespace: pi-job-test
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4

