apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: brian@bjdazure.tech
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: kong
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: grpc-bjdazure-tech-tls
spec:
  secretName: grpc-bjdazure-tech-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: grpc.bjdazure.tech
  dnsNames:
  -  grpc.bjdazure.tech
