apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpbin
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - name: httpbin
        #image: bjd145/httpbin:1087
        image: bjd145/whatos:e7fbcf6f2122
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        resources:
          limits:
            memory: "512Mi"
            cpu: "2"
          requests:
            memory: "64Mi"
            cpu: "0.25"
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: app
spec:
  selector:
    app: httpbin
  ports:
  - port: 8080
    targetPort: 8081