apiVersion: fleet.azure.com/v1alpha1
kind: ClusterResourcePlacement
metadata:
  name: app-west
spec:
  resourceSelectors:
    - group: ""
      version: v1
      kind: Namespace
      name: app
  policy:
    affinity:
      clusterAffinity:
        clusterSelectorTerms:
          - labelSelector:
              matchLabels:
                fleet.azure.com/location: westus3
---
apiVersion: fleet.azure.com/v1alpha1
kind: ClusterResourcePlacement
metadata:
  name: app-southcentral
spec:
  resourceSelectors:
    - group: ""
      version: v1
      kind: Namespace
      name: app
  policy:
    affinity:
      clusterAffinity:
        clusterSelectorTerms:
          - labelSelector:
              matchLabels:
                fleet.azure.com/location: southcentralus
