version: '3'

tasks:
  up:
    desc: Creates a complete Azure Container App Environment with Workload Profile
    cmds:
    - task: init
    - task: apply

  init:
    desc: Initializes Terraform 
    cmds:
    - terraform workspace new {{.REGION}} || true
    - terraform workspace select {{.REGION}}
    - terraform init
    vars: 
      REGION: '{{default "southcentralus" .CLI_ARGS}}'
  
  apply:
    desc: Applies Terraform 
    cmds:
    - terraform apply -auto-approve -var "region={{.REGION}}" -compact-warnings
    vars: 
      REGION: '{{default "southcentralus" .CLI_ARGS}}'

  validate:
    desc: Validates proper deployment 
    cmds:
    - echo "Running abritary commands with options is not supported by - az containerapp exec"
    - echo "Try the following inside the container - nslookup httpbin ; curl http://httpbin/html"
    - az containerapp exec --name utils --resource-group {{.RG}} --command bash
    vars:
      RG: 
        sh: terraform  output -raw RESOURCE_GROUP

  down:
    desc: Destroys all Azure resources and cleans up Terraform
    cmds:
    - rm -rf terraform.tfstate.d .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info
    - az group delete -n {{.RG}} --yes --no-wait || true
    vars:
      RG: 
        sh: terraform  output -raw RESOURCE_GROUP
