
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  name: cosmosdb002
  namespace: default
spec:
  clusterServiceClassExternalName: azure-cosmosdb-sql
  clusterServicePlanExternalName: sql-api
  parameters:
    location: centralus
    resourceGroup: DevSub02_Cosmos_RG
    consistencyPolicy:
      defaultConsistencyLevel: Eventual
    multipleWriteRegionsEnabled: enabled
    #    readRegions: [ eastus2, westus ]
