---
apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: crossplane-stable
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.crossplane.io/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: crossplane-system
  chart:
    spec:
      chart: crossplane
      version: '1.10.2'
      sourceRef:
        kind: HelmRepository
        name: crossplane-stable
        namespace: flux-system
      interval: 1m
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-terraform
  namespace: crossplane-system
spec:
  package: xpkg.upbound.io/upbound/provider-terraform:0.4.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azure
  namespace: crossplane-system
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-azure:v0.20.1
  