---
apiVersion: v1
kind: Namespace
metadata:
  name: crossplane-system
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: crossplane-stable
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://charts.crossplane.io/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: crossplane
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: crossplane-syste
  chart:
    spec:
      chart: crossplane-stable/crossplane
      version: '1.1.0'
      sourceRef:
        kind: HelmRepository
        name: kubevela
        namespace: flux-system
      interval: 1m
