apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname-podid
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: "bjdkv-b25e5d"
    objects:  |
      array:
        - |
          objectName: psql
          objectType: secret                    
    tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"
