apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-blob
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain  
  storageClassName: azureblob-fuse-premium
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    volumeHandle: hound50021sa_test2
    volumeAttributes:
      resourceGroup: hound-Core_Storage_RG
      storageAccount:  bjdterraform003
      containerName: plans
      AzureStorageAuthType: "key"
      keyVaultURL: https://hound-50021-kv.vault.azure.net
      keyVaultSecretName:  storage-account-key
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-blob
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-blob
  storageClassName: azureblob-fuse-premium
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hound-50021-app-identity
  annotations:
    azure.workload.identity/client-id: 634c9b3d-bd2d-455e-b7fa-1f707425bb36
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blobfuse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blobfuse
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: blobfuse
    spec:
      serviceAccountName: hound-50021-app-identity
      containers:
      - image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
        name: blobfuse-test
        volumeMounts:
        - name: persistent-storage
          mountPath: "/mnt/blob"
          readOnly: false
        resources:
          limits:
            memory: "512Mi"
            cpu: "2"
          requests:
            memory: "64Mi"
            cpu: "0.25"
      volumes:
      - name: persistent-storage
        persistentVolumeClaim:
          claimName: pvc-blob