apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bjd-azurefiles1tb-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: bjd-azurefiles
  resources:
    requests:
      storage: 1000Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: bjdutils1tb-azfiles
spec:
  containers:
  - name: bjdutils1tb-azfiles
    image: bjd145/utils:2.5
    volumeMounts:
    - mountPath: "/mnt/files"
      name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: bjd-azurefiles1tb-pvc
