apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-managed-files
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azurefile-csi-premium
  resources:
    requests:
     storage: 50Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-files
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  containers:
    - name: myfrontend
      image: mcr.microsoft.com/oss/nginx/nginx:1.15.5-alpine
      volumeMounts:
      - mountPath: "/mnt/azure"
        name: volume
  volumes:
    - name: volume
      persistentVolumeClaim:
        claimName: azure-managed-files
