version: '3'

env:
  ACR_NAME: bjdcsa
  ACR_RG: Core_ContainerRepo_RG
  AKS_NAME: phoenix-26877-aks
  AKS_RG: phoenix-26877-aks_rg
  AKS_EGRESS_IP: 52.248.98.206
  AI_NAME: phoenix-26877-appinsights
  AI_RG: phoenix-26877-aks_rg
  COMMIT_VERSION: workloadid-9cc7fb7f16eg
  
tasks:
  up:
    desc: Creates Azure infrastructure and deploys application code
    cmds:
    - terraform -chdir=./infrastructure init
    - terraform -chdir=./infrastructure apply  -var "aks_name={{.AKS_NAME}}"  -var "aks_rg_name={{.AKS_RG}}"  -var "aks_ip_address={{.AKS_EGRESS_IP}}" -var "ai_name={{.AI_NAME}}"  -var "ai_rg_name={{.AI_RG}}" -auto-approve
    - task: deploy

  deploy:
    desc: Deploys Todo application via Helm
    cmds:
    - helm upgrade -i workloadid --set ACR_NAME="{{.ACR_NAME}}" --set COMMIT_VERSION={{.COMMIT_VERSION}} --set APP_NAME={{.APP_NAME}} --set ARM_WORKLOAD_APP_ID={{.ARM_WORKLOAD_APP_ID}} --set ARM_TENANT_ID={{.ARM_TENANT_ID}} --set APP_INSIGHTS="{{.APP_INSIGHTS}}" ./chart
    vars:
      APP_NAME: 
        sh: terraform -chdir=./infrastructure output -raw APP_NAME
      ARM_WORKLOAD_APP_ID: 
        sh: terraform -chdir=./infrastructure output -raw ARM_WORKLOAD_APP_ID
      ARM_TENANT_ID:
        sh: terraform -chdir=./infrastructure output -raw ARM_TENANT_ID
      APP_INSIGHTS:
        sh: terraform -chdir=./infrastructure output -raw APP_INSIGHTS

  down:
    desc: Destroys all Azure resources and cleans up Terraform
    cmds:
    - az group list --tag Application="Todo Demo App" --query "[].name" -o tsv | xargs -ot -n 1 az group delete -y --verbose --no-wait -n || true
    - cd infrastructure ; 
      rm -rf terraform.tfstate.d .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info || true
    vars:
      RG:
        sh: terraform  output -raw RESOURCE_GROUP
