apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
 name: demo-aad1
spec:
  type: 0
  ResourceID: /subscriptions/<sub.id>/resourcegroups/<MC_AKS_Resouces_RG_Name>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<MSI_Name>
  ClientID: <ClientId>
