apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: golangexample
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: golangexample
    spec:
      containers:
      - name: golangexample
        image: bjd145.azurecr.io/golangrestapi:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: registrykey
