apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: csi-identity
spec:
  type: 0
  clientID: 6fa79e6f-b8a4-44f7-887f-{uuid}
  resourceID: /subscriptions/{sub}/resourceGroups/{rg}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/csi-example-reader
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: csi-identity-binding
spec:
  azureIdentity: csi-identity
  selector:  csi-pod-selector