apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname-podid
spec:
  provider: azure
  parameters:
    usePodIdentity: "true"
    keyvaultName: "bjdappkeyvault095"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: csi-secret-example
          objectType: secret                    
          objectVersion: ""                    
    tenantId: "{uuid}"
