apiVersion: v1
kind: Pod
metadata:
  name: random-generator
  labels:
    app: random-generator
spec:
    containers:
    - name: random-generator
      image: k8spatterns/random-generator:1.0
      volumeMounts:
        - name: pod-info
          mountPath: /pod-info
    volumes:
      - name: pod-info
        downwardAPI:
          items:
          - path: labels
            fieldRef:
              fieldPath: metadata.labels
          - path: annotations
            fieldRef:
              fieldPath: metadata.annotations 