apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-promtheus-demo
  namespace: {{ .Values.NAMESPACE }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: otel-demo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: otel-demo
        azure.workload.identity/use: "true"
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: {{ .Values.WORKLOAD_ID.NAME }}
      containers:
      - name: otel-demo
        image: {{ print .Values.ACR.NAME "/otel-promtheus-demo:" .Values.GIT_COMMIT_VERSION }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.SERVICE_PORT }}
        resources:
          limits:
            memory: "512Mi"
            cpu: "2"
          requests:
            memory: "64Mi"
            cpu: "0.25"
---
apiVersion: v1
kind: Service
metadata:
  name: otel-demo-svc
  namespace: {{ .Values.NAMESPACE }}
  annotations:
   service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  selector:
    app: otel-demo
  ports:
  - port: 80
    targetPort: {{ .Values.SERVICE_PORT }}
  type: LoadBalancer
