kind: Pod
apiVersion: v1
metadata:
  name: fiopod
  namespace: default
spec:
  nodeSelector:
    acstor.azure.com/io-engine: acstor
  volumes:
    - name: azurediskpv
      persistentVolumeClaim:
        claimName: azurediskpvc
  containers:
    - name: fio
      image: nixery.dev/shell/fio
      args:
        - sleep
        - "1000000"
      resources:
        limits:
          cpu: "2"
          memory: "2Gi"
      volumeMounts:
        - mountPath: "/volume"
          name: azurediskpv