apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: nginx-ingress
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: certificates@example.guru
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}