apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: letsencrypt-staging
  namespace: ingress-nginx
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: certificates@ancientrome.guru
    privateKeySecretRef:
      name: letsencrypt-staging
    http01: {}