apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: clippy-ancientrome-guru
  namespace: ingress-nginx
spec:
  secretName: clippy-ancientrome-guru-tls
  issuerRef:
    name: letsencrypt-staging
  commonName: clippy.ancientrome.guru
  dnsNames:
  -  clippy.ancientrome.guru
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - clippy.ancientrome.guru