apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  namespace: nginx-ingress
  annotations:
   nginx.ingress.kubernetes.io/rewrite-target: /
   kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - clippy.example.guru
    secretName: clippy-example-guru-tls
  rules:
  - host: clippy.example.guru
    http:
     paths:
     - backend:
        serviceName: party-clippy
        servicePort: 80
