version: '3'

tasks:
  up:
    desc: Creates a complete Azure ML environment 
    cmds:
    - terraform workspace new {{.REGION}} || true
    - terraform workspace select {{.REGION}}
    - terraform init
    - terraform apply -auto-approve -var "region={{.REGION}}" -compact-warnings
    - task: creds
    vars: 
      REGION: '{{default "southcentralus" .CLI_ARGS}}'

  creds:
    desc: Gets AKS credential file
    cmds:
    - az aks get-credentials -g {{.RG}} -n {{.AKS}} --overwrite-existing
    - sed -i s/devicecode/azurecli/g ~/.kube/config
    vars:
      RG: 
        sh: terraform output -raw AKS_RESOURCE_GROUP
      AKS: 
        sh: terraform output -raw AKS_CLUSTER_NAME

  # radius:
  #   desc: Initialize Radius 
  #   cmds:
  #   - rad install kubernetes
  #   - rad group create -g {{.RG}}
  #   - rad credential register azure --client-id $ARM_CLIENT_ID --client-secret $ARM_CLIENT_SECRET --tenant-id $ARM_TENANT_ID
  #   - rad workspace create kubernetes -w {{.APP_NAME}} --force
  #   - rad env create {{.APP_NAME}} -g {{.RG}} -n {{.APP_NAME}} -w {{.APP_NAME}}
  #   vars:
  #     RG: 
  #       sh: terraform output -raw AKS_RESOURCE_GROUP
  #     APP_NAME:
  #       sh: terraform output -raw APP_NAME

  # eshop:
  #   desc: Deploys eshop-dapr via Project Radius
  #   dir: ./app
  #   cmds:
  #   - rad run dapr.bicep --application {{.APP_NAME}}
  #   vars:
  #     OIDC:
  #       sh: terraform -chdir=../. output -raw AKS_OIDC_ISSUER
  #     RG: 
  #       sh: terraform -chdir=../. output -raw AKS_RESOURCE_GROUP
  #     APP_NAME:
  #       sh: terraform -chdir=../. output -raw APP_NAME

  down:
    desc: Destroys all Azure resources and cleans up Terraform
    cmds:
    - rm -rf terraform.tfstate.d .terraform.lock.hcl .terraform terraform.tfstate terraform.tfstate.backup .terraform.tfstate.lock.info
    - az group delete -n {{.RG}} --yes || true
    vars:
      RG: 
        sh: terraform  output -raw AKS_RESOURCE_GROUP