apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: greetingshelm
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: greetingshelm
    spec:
      containers:
      - name: greetingshelm
        image: bjd145.azurecr.io/golangrestapi:{{.Values.buildid}} 
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1000
          runAsNonRoot: true
          readOnlyRootFilesystem: true
        ports:
        - containerPort: 5000
        env:
        - name: VERSION
          valueFrom:
            configMapKeyRef:
                name: greetingshelm
                key: build.version
        resources:
          limits:
            memory: "512Mi"
            cpu: "2"
          requests:
            memory: "128Mi"
            cpu: "0.5"
      imagePullSecrets:
        - name: registrykey
---
apiVersion: v1
kind: Service
metadata:
  name: greetingshelmsvc
  labels:
    version: golang
spec:
  selector:
    app: greetingshelm
  ports:
  - port: 8080
    targetPort: 5000
  type: LoadBalancer
